### ISSUE TITLE
Music index not sync

### ISSUE THREAD

**Issue by n0uur** [LoukHin/probably-a-music-bot#3]
![image](https://github.com/loukhin/probably-a-music-bot/assets/50010805/fa6e380d-02a1-4153-9e56-7ca72917139a)

Showing music index on queue list not sync with `/remove` command. (still cannot reproduce, but will happen when have a lot of music in queue)

**Comment by loukhin** [comment]
Should be fixed with https://github.com/loukhin/probably-a-music-bot/commit/7302602db971360b74e6a3e3afa9562ef604e092
